

Homepage
    `2017.compciv.org <https://2017.compciv.org>`_

    Listing: COMM 113/213

Class
    McClatchy Hall, Building 120, Room 410

    Tuesdays/Thursdays, 1:30PM to 2:50



Instructor:
    Dan Nguyen
    Lorry I. Lokey Visiting Professor in Professional Journalism

    dun@stanford.edu
    `@dancow <https://twitter.com/dancow>`_
    Room 342, McClatchy Hall

Office:
    McClatchy Hall, Room 342

    After class or by appointment.
