************************************
Academic Expectations and Evaluation
************************************


Grading policy
==============

No curve and no exams.

Visit the :doc:`/syllabus/assignments/index` page for more details on how your work will be assessed.

.. csv-table::
    :title: Rubric
    :widths: 70,30

    Homework,30%
    Projects,40%
    Quizzes,20%
    Attendance,10%

.. csv-table::
    :title: Scale
    :widths: 50,50

    A,90% <
    B,80% <
    C,70% <
    D,60% <






The Honor Code
--------------

You are expected to adhere to the `Stanford University Honor Code <https://ed.stanford.edu/academics/masters-handbook/honor-code>`.

That said, there are a few things unique to this course that make it pointless to bend the rules by Googling for help.

So don't cheat, because you're obligated to follow Stanford's expectations of integrity and honesty. But also, because you'd save time by just asking me for help.



Disabilities and other accommodations
-------------------------------------

If you need accommodations because of a disability, please register with the `Stanford Office of Accessible Education <https://undergrad.stanford.edu/planning/academic-policies/students-disabilities>`.



