
Grading policy
==============

No curve and no exams.

You are expected to adhere to the `Stanford University Honor Code <https://ed.stanford.edu/academics/masters-handbook/honor-code>`_.



Weights
-------

.. csv-table::
    :widths: 70,30

    Homework,30%
    Projects,40%
    Quizzes,20%
    Attendance,10%


Grading scale
-------------

.. csv-table::
    :widths: 50,50

    A,"90% <"
    B,"80% <"
    C,"70% <"
    D,"60% <"


Visit the :doc:`/syllabus/assignments/index` page for more details on how homework, projects, and quizzes will be assessed.


Attendance
----------

1 point for the day if you're in class. you get 1 point for the day. 0 otherwise.

For any in-class assignments such as missing a quiz, you can have a make-up quiz **if you have given notice at least 2 days in advance**.


Late policy
-----------

Late assignments can receive as much as 80% of the max score if turned in within 48 hours of the due date.


Disabilities and other accommodations
-------------------------------------

If you need accommodations because of a disability, please register with the `Stanford Office of Accessible Education <https://undergrad.stanford.edu/planning/academic-policies/students-disabilities>`.




